services:
  - type: web
    name: solana-watcher
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn solana_watcher:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: RECEIVER
        sync: false
      - key: CHANNEL_NAME
        sync: false
