services:
  - type: web
    name: solana-watcher-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python solana_watcher.py
    autoDeploy: true
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: RECEIVER
        value: your_username
      - key: CHANNEL_NAME
        value: channel_name_without_@
