services:
  - type: web
    name: solana-watcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn solana_watcher:app --host 0.0.0.0 --port 10000
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: SESSION_B64
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
      - key: RECEIVER
        sync: false
