services:
  - type: web
    name: solana-watcher-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python solana_watcher.py
    autoDeploy: true
    healthCheckPath: ""  # This disables Render's port check (your bot doesn't need a port)
    envVars:
      - key: API_ID
        value: YOUR_API_ID_HERE
      - key: API_HASH
        value: YOUR_API_HASH_HERE
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN_HERE
      - key: RECEIVER
        value: YOUR_TELEGRAM_USERNAME_HERE
      - key: CHANNEL_NAME
        value: CHANNEL_TO_WATCH
